"""add asset snapshot table

Revision ID: 00437f66566a
Revises: 56c56909b922
Create Date: 2026-03-12 23:31:07.410478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00437f66566a'
down_revision: Union[str, Sequence[str], None] = '56c56909b922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_net_worth', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='_user_date_uc')
    )
    op.create_index(op.f('ix_asset_snapshots_id'), 'asset_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_snapshot_date'), 'asset_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_user_id'), 'asset_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_snapshots_user_id'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_snapshot_date'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_id'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ###
